# Generated by Django 5.0.4 on 2024-05-01 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Roads',
        ),
        migrations.AddField(
            model_name='point',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masark.road'),
        ),
    ]
